# Generated by Django 3.2.6 on 2023-06-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decreto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lei', models.TextField(verbose_name=256)),
                ('leiClean', models.TextField()),
                ('ano', models.IntegerField()),
                ('ementa', models.TextField()),
                ('ementaClean', models.TextField()),
                ('inteiroTeor', models.TextField()),
                ('inteiroTeorClean', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LeiOrdinaria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lei', models.TextField()),
                ('leiClean', models.TextField()),
                ('ano', models.IntegerField()),
                ('ementa', models.TextField()),
                ('ementaClean', models.TextField()),
                ('inteiroTeor', models.TextField()),
                ('inteiroTeorClean', models.TextField()),
            ],
        ),
    ]
