# Generated by Django 4.1.5 on 2023-01-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecretoPresidencial',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ano', models.IntegerField()),
                ('lei', models.TextField()),
                ('ementa', models.TextField()),
                ('inteiroTeor', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='DecretosPresidenciais',
        ),
    ]
