# Generated by Django 3.2.6 on 2023-06-04 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decreto',
            name='ementaClean',
        ),
        migrations.RemoveField(
            model_name='decreto',
            name='inteiroTeorClean',
        ),
        migrations.RemoveField(
            model_name='decreto',
            name='leiClean',
        ),
        migrations.RemoveField(
            model_name='leiordinaria',
            name='ementaClean',
        ),
        migrations.RemoveField(
            model_name='leiordinaria',
            name='inteiroTeorClean',
        ),
        migrations.RemoveField(
            model_name='leiordinaria',
            name='leiClean',
        ),
    ]
