# Generated by Django 4.1.5 on 2023-01-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_decretopresidencial_delete_decretospresidenciais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decretopresidencial',
            name='id',
        ),
        migrations.AlterField(
            model_name='decretopresidencial',
            name='lei',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
