# Generated by Django 3.2.6 on 2023-12-22 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230604_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decreto',
            name='lei',
            field=models.TextField(),
        ),
    ]
