# Generated by Django 4.1.5 on 2023-01-05 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_decretopresidencial_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DecretoPresidencial',
        ),
    ]
