# Generated by Django 4.1.5 on 2023-01-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_decretopresidencial_decretoid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decretopresidencial',
            name='decretoId',
            field=models.AutoField(default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
