# Generated by Django 4.1.5 on 2023-01-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_decretopresidencial_decretoid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decretopresidencial',
            name='decretoId',
        ),
        migrations.AlterField(
            model_name='decretopresidencial',
            name='lei',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
