# Generated by Django 4.1.5 on 2023-01-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_decreto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DecretoPresidencial',
        ),
    ]
