# Generated by Django 4.1.5 on 2023-01-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_delete_decretopresidencial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeiOrdinaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lei', models.TextField()),
                ('ano', models.IntegerField()),
                ('ementa', models.TextField()),
                ('inteiroTeor', models.TextField()),
            ],
        ),
    ]
