# Generated by Django 4.1.5 on 2023-01-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_leiordinaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='decreto',
            name='ementaClean',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decreto',
            name='inteiroTeorClean',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decreto',
            name='leiClean',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
