# Generated by Django 4.1.5 on 2023-01-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_decreto_ementaclean_decreto_inteiroteorclean_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leiordinaria',
            name='ementaClean',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leiordinaria',
            name='inteiroTeorClean',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leiordinaria',
            name='leiClean',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
